export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	GET_USERS: 'GET_USERS',
	LOAD_POST: 'LOAD_POST',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_COMMENTS_DATA: 'SET_COMMENTS_DATA',
	ADD_COMMENT_DATA: 'ADD_COMMENT_DATA',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
};
