export const OPERATIONS = {
	AUTHORIZE: 'authorize',
	LOGOUT: 'logout',
	REGISTER: 'register',
	FETCH_ROLES: 'fetchRoles',
	FETCH_USERS: 'fetchUsers',
	UPDATE_USER: 'updateUser',
	REMOVE_USER: 'removeUser',
	FETCH_POST: 'fetchPost',
	ADD_COMMENT: 'addComment',
	FETCH_COMMENTS: 'fetchComments',
	REMOVE_COMMENT: 'removeComment',
	SAVE_POST: 'savePost',
	REMOVE_POST: 'removePost',
};
